[package]
name = "auto_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
indicatif = "0.17.3"
structopt = "0.3.26"
tokio = { version = "1.25.0", features = ["full"] }
